name: CI/CD Pipeline

on:
  push:
    branches:
      - feature-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.21.3'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      # Set up SSH Agent for SSH key
      - name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # Ensure SSH host is known
      - name: Add SSH key to known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Sync build directory to server
      - name: Sync build directory to server
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/path/to/your/deployment/directory

      # Upload .env file to server
      - name: Upload .env file to server
        run: scp -P ${{ secrets.SSH_PORT }} .env ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/path/to/your/deployment/directory
