name: Continuous Deployment Workflow QA

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    name: 'Builds the strapi CMS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '22.12.0'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

  deploy:
    name: 'Deploy to QA'
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 5
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Deploy to QA
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.QA_SERVER }}
          username: ${{ secrets.QA_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.QA_PORT }}
          command_timeout: 30m
          script: |
            source .bashrc
            source .profile
            rm -rf cms.old
            mv zoonotify-cms cms.old
            git clone https://github.com/SiLeBAT/zoonotify-cms.git
            cp env.qa ${{ secrets.QA_PATH }}/.env
            cd ${{ secrets.QA_PATH }}
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git pull
            ./deploy.sh

