name: CI/CD Pipeline for QA

on:
  push:
    branches:
      - testBranch92
  pull_request:
    branches:
      -develop

jobs:
  build:
    name: 'Builds the strapi CMS'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.15.0'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build

