name: Continuous Integration Workflow

# This workflow is triggered whenever a new PR is created on the develop branch
on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
# Run the linter to check for code style issues
  lint:
    name: 'Run linter'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12.0'

      - name: Install dependencies
        run: yarn

# Run unit tests to make sure everything is OK

